# Build the ColorPicker project utilizing npm and MSBuild
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

#COLOR PICKER

steps:
#Run npm install to get all required resources for the projectl
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './ColorPicker/'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './BooleanOptionset/'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './BingMapsGrid/'

#PowerApps controls can be build using MSBuild and do not require the PCF CLI to be downloaded.
#The build command will utilize NuGet to go out and get all the resource packages it needs.
- task: MSBuild@1
  inputs:
    solution: '**/*.cdsproj'
    msbuildArguments: '/t:build /restore'

#Copy the solution files to the build artifacts directory.
- task: CopyFiles@2
  inputs:
    SourceFolder: './ColorPicker/ColorPicker/ControlPicker/bin/Debug/'
    Contents: 'ControlPicker.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './BooleanOptionset/BooleanOptionset/BooleanOptionsetControl/bin/Debug/'
    Contents: 'BooleanOptionsetControl.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './BingMapsGrid/BingMapsGrid/BingMapsGridControl/bin/Debug/'
    Contents: 'BingMapsGrid.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

#Publish the build artifacts.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

#GitHub Release
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_rwilson504'
    repositoryName: 'rwilson504/PCFControls'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'